recipe: default.v1
language: en
pipeline:
- name: KeywordIntentClassifier
- name: NLUCommandAdapter
- name: LLMCommandGenerator
  llm:
    model_name: gpt-4
    request_timeout: 7

policies:
- name: rasa.core.policies.flow_policy.FlowPolicy
  max_distance: 0.2
- name: rasa_plus.ml.IntentlessPolicy

#  - name: RulePolicy
assistant_id: 20231120-125729-alternating-exchange
